#!/bin/sh

if ! command -V sudo; then
  apt-get update
  apt-get install -y --no-install-recommends sudo
fi

sudo apt-get update -q -y
sudo apt-get install cmake openssl libssl-dev pkg-config curl -q -y
